POST http://localhost:3001/api/persons
# spcify http header
Content-Type: application/json 

{"name":"test","number":"123456789"}


###
POST http://localhost:3001/api/persons
# spcify http header
Content-Type: application/json 

{"name":"Arto Hellas", "number":"040-123456"}

###
POST http://localhost:3001/api/persons
# spcify http header
Content-Type: application/json 

{"name":"test"}


###
GET http://localhost:3001/api/persons


###
GET http://localhost:3001/api/persons/1


###
DELETE http://localhost:3001/api/persons/6320e5ea394aae1e8a171d91